// ============================================================================
// generate.mjs — convert the canonical Qurbaqa OKLCH source (src/qurbaqa.source.mjs)
// into sRGB hex tables for React Native, written to src/generated/qurbaqa.ts.
//
// Dependency-free: implements OKLCH -> OKLab -> linear sRGB -> gamma sRGB -> hex
// (Björn Ottosson's Oklab matrices), clamping to the sRGB gamut. RN cannot parse
// oklch(), so native consumes these precomputed hex values.
//
// Run: node scripts/generate.mjs   (also runs as part of `pnpm build` prestep)
// ============================================================================

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import * as src from '../src/qurbaqa.source.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, '../src/generated');
const OUT_FILE = resolve(OUT_DIR, 'qurbaqa.ts');

/** OKLCH [L,C,H(deg)] -> #rrggbb (clamped to sRGB). */
function oklchToHex([L, C, H]) {
  const hr = (H * Math.PI) / 180;
  const a = C * Math.cos(hr);
  const b = C * Math.sin(hr);

  // OKLab -> LMS (cube roots undone)
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3;
  const m = m_ ** 3;
  const s = s_ ** 3;

  // LMS -> linear sRGB
  let r = +4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
  let g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
  let bl = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;

  // linear -> gamma sRGB
  const gamma = (x) => {
    const c = Math.min(1, Math.max(0, x));
    return c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055;
  };
  const to255 = (x) => Math.round(gamma(x) * 255);
  const hex = (n) => n.toString(16).padStart(2, '0');
  return `#${hex(to255(r))}${hex(to255(g))}${hex(to255(bl))}`;
}

function mapToHex(obj) {
  return Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, oklchToHex(v)]));
}

const darkColors = { ...mapToHex(src.shared), ...mapToHex(src.dark) };
const lightColors = { ...mapToHex(src.shared), ...mapToHex(src.light) };

const banner = `// AUTO-GENERATED by scripts/generate.mjs — DO NOT EDIT BY HAND.\n// Source of truth: src/qurbaqa.source.mjs (OKLCH). Regenerate: node scripts/generate.mjs\n`;

// Fixed token-key union so both light and dark share one type (values are plain
// strings, not narrow hex literals — light and dark differ, so a literal type
// would make the two schemes incompatible).
const tokenUnion = Object.keys(darkColors)
  .map((k) => `'${k}'`)
  .join(' | ');

const body = `${banner}
export type QurbaqaColorToken = ${tokenUnion};
export type QurbaqaColors = Record<QurbaqaColorToken, string>;

export const qurbaqaColors: { dark: QurbaqaColors; light: QurbaqaColors } = {
  dark: ${JSON.stringify(darkColors, null, 2)},
  light: ${JSON.stringify(lightColors, null, 2)},
};

export type QurbaqaColorScheme = keyof typeof qurbaqaColors;

export const qurbaqaRadii = ${JSON.stringify(src.radii, null, 2)} as const;
export const qurbaqaShadows = ${JSON.stringify(src.shadows, null, 2)} as const;
export const qurbaqaFonts = ${JSON.stringify(src.fonts, null, 2)} as const;
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, body);

// Console summary for verification.
console.log('Generated', OUT_FILE);
console.log('  brand500 (dark):', darkColors.brand500, ' cFinance:', darkColors.cFinance);
console.log('  bg dark:', darkColors.bg, ' bg light:', lightColors.bg);
console.log('  pos:', darkColors.pos, ' neg:', darkColors.neg, ' warn:', darkColors.warn);
